# tx: 47b47334e802b43ba508a8ac17eaaa12b27e68f161707c6f454559a5405e8070
project: DogeADA

categories:
  - Meme
  - Other

socialLinks:
  twitter: https://x.com/Doge_ada
  discord: https://discord.gg/vYHXWrXR

decimals: 0

verified: true
