name: CI
on:
  pull_request:
    branches:
      - "*"
  push:
jobs:
  validate-data:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            tokens:
              - 'src/tokens/**'
          base: 'tlinh'
      - name: Run validate data
        if: steps.changes.outputs.tokens == 'true'
        working-directory: src/tokens
        run: pnpm run test
